    street_addy:
      desc: Property street address
      type: String
      value: "1234 Hocus Potato Way"
    city:
      desc: "Property city"
      type: String
      value: "Tatertown"
    max_age:
      type: Integer
      value: 110
    max_amount:
      desc: "Maximum loan amount in dollars"
      type: Integer
      value: 467000
    max_income:
      desc: "Maximum applicant income in thousands"
      type: Integer
      value: 300
    max_rs:
      desc: "Maximum rate spread"
      type: Integer
      value: 100
    max_credit_score:
      desc: "Maximum credit score"
      type: Integer
      value: 840
    min_credit_score:
      desc: "Minimum credit score"
      type: Integer
      value: 650
    loan_costs:
      desc: "Maximum loan costs"
      type: Integer
      value: 10000
    points_and_fees:
      desc: "Maximum points and fees"
      type: Integer
      value: 10000
    orig_charges:
      desc: "Maximum origination charges"
      type: Integer
      value: 10000
    discount_points:
      desc: "Maximum discount points cost"
      type: Integer
      value: 10000
    lender_credits:
      desc: "Maximum lender credits"
      type: Integer
      value: 10000
    interest_rate:
      desc: "Maximum interest rate"
      type: Integer
      value: 25
    penalty_max:
      desc: "Maximum prepayment penalty term"
      type: Integer
      value: 36
    dti:
      desc: "Maximum debt to income ratio"
      type: Integer
      value: 100
    cltv:
      desc: "Combinted loan to value ratio"
      type: Integer
      value: 120
    loan_term:
      desc: "Maximum loan term"
      type: Integer
      value: 360
    intro_rate:
      desc: "Maximum introductory rate period"
      type: Intger
      value: 36
    max_units:
      desc: "Maximum total units"
      type: Integer
      value: 30
    prop_val_max:
      desc: "Maximum property value in dollars"
      type: Integer
      value: 1000000
    prop_val_min:
      desc: "Minimum property value in dollars"
      type: Integer
      value: 100000
    file_length:
     desc: "The number of lines in the clean data file"
     type: Integer
     value: 100
    clean_file:
     type: File
     value: "clean_file_100_rows.txt"
